### ISSUE TITLE
Initial prevStrHash should be a seed

### ISSUE THREAD

**Issue by masomel** [coniks-sys/libmerkleprefixtree-go#20]
This should address https://github.com/coniks-sys/libmerkleprefixtree-go/pull/8#discussion_r70639162

**Comment by masomel** [comment]
Per https://github.com/coniks-sys/libmerkleprefixtree-go/pull/8#issuecomment-233026939 this seems to be addressed. @arlolra Did you have something else in mind?

**Comment by arlolra** [comment]
LGTM
