### ISSUE TITLE
Implement STR

### ISSUE THREAD

**Issue by masomel** [coniks-sys/libmerkleprefixtree-go#3]
Implement the signed tree root data structure per the most recent version of the [CONIKS paper](http://eprint.iacr.org/2014/1004). This includes the hash chain of signed tree roots that forms the history.

**Comment by c633** [comment]
I updated the `AuthenticationPath` source code and tree.`Get()` method to make it match/more suitable for Key Lookup function in da09f7ad7008b631cdd6e80fe4649979837f7a3a.
The Key Lookup function is implemented in [`lookup`](https://github.com/coniks-sys/libconiks-server-go/commit/b83794d58ce058a126f94dd20b3e5bee2f30b00b) branch.

**Comment by masomel** [comment]
The changes in da09f7a make sense to me. I'll go take a look at the [lookup](https://github.com/coniks-sys/libconiks-server-go/commit/b83794d58ce058a126f94dd20b3e5bee2f30b00b) branch.
