### ISSUE TITLE
Add VRF implementation

### ISSUE THREAD

**Issue by masomel** [coniks-sys/libmerkleprefixtree-go#5]
Currently, the private index is computed only using a cryptographic hash. This will also require adding a VRF key field in the STR policy.

**Comment by Liamsi** [comment]
I'll create a PR later today (if no-one else already started working on this)

**Comment by Liamsi** [comment]
I've added a branch with with the coname's VRF implementation  (almost unmodified): 
https://github.com/coniks-sys/libmerkleprefixtree-go/tree/vrf_impl_coname_agl
and a branch where I changed their code such that it should be exactly the implemetation from CONIKS paper:
https://github.com/coniks-sys/libmerkleprefixtree-go/tree/orig_coniks_vrf

There is no PR (yet) as I first wanted to examine/discuss if their changes bring any security benefits. But if you prefer Bonneau's orig. proposal in the CONIKS paper I can creat a PR from the 2nd branch.

**Comment by Liamsi** [comment]
The main difference of the coname/dename VRF implementation to the one in the CONIKS paper is:
the VRF is defined as
VRF_k(m) = h(m, H(m)^k) instead of VRF_k(m) = H_1(m)^k
(where h is sha3 and H(m):=f(h(m))^8 (with f being the elligator map)). 
Additionally to s and t in the proof they return ii:=H(m)^k.

Everything else is equivalent. I remember @andres-erbsen and @daniel-ziegler mentioning they did some modifications to the original VRF construction to prevent some collision attacks. I'll ask them for some more details/links on that.

**Comment by masomel** [comment]
If
> VRF_k(m) = h(m, H(m)^k) ... where h is sha3

does coname/dename subsequently still hash the result of VRF_k(m) to compute the private index?

**Comment by masomel** [comment]
Looping @jcb82 into this discussion.

Joe did go back and address collision attacks in the Merkle tree design (which is where the tree nonce etc came from), but I can't recall if he modified the VRF design as well. I also know he was in contact with the coname authors last summer, though I don't know to which extent they worked together on the modifications to the VRF construction.

**Comment by Liamsi** [comment]
> does coname/dename subsequently still hash the result of VRF_k(m) to compute the private index?

No it doesn't. So to be more precise while in CONIKS the index is computed by 
i = H(VRF_k (u)) = H(H_1(m)^k) 
in coname it is computed by 
i = h(m, H(m)^k)

**Comment by masomel** [comment]
> No it doesn't the (already hashed VRF output) again.
To be a little more precise: while in CONIKS the index is computed by
i = H(VRF_k (u)) = H(H_1(m)^k)
in coname it is computed by
i = h(m, H(m)^k)

Ok, that's what I thought, but I wanted to confirm. I honestly don't know enough about either VRF construction to determine how well they compare in terms of security. A write-up about coname's construction would be helpful.

**Comment by Liamsi** [comment]
Adding @jcb82 comment regarding the VRF construction: 

> I can chime in to say the addition of the name in the outer hash is to (further) protect against collisions in the elligator map. If you could find n1, n2 such that f(h(n1))^8 = f(h(n2))^8, then this extra hash with the name would still prevent the two from having the same VRF result so you get "full strength" against collisions from the underlying hash.

**Comment by masomel** [comment]
So it looks like it makes sense to go with coname's VRF.

**Comment by masomel** [comment]
Closed in 8d3acff
