### ISSUE TITLE
Is the empty/different leaf node in a proof of absence enough?

### ISSUE THREAD

**Issue by masomel** [coniks-sys/libmerkleprefixtree-go#7]
Should the client have some way of verifying that the index **j** of the different leaf (or empty node) in a proof of absence is indeed a prefix match for the index **i** of the key it tried to look up? Without this, a malicious provider could return a valid auth path in the tree as a proof of absence, even though **i** *does* exist in the tree, to deny service to the client. 

On the other hand, returning the index **i** for each failed lookup may allow an attacker to slowly enumerate the entire index space.

**Comment by masomel** [comment]
Since a proof of absence contains the full index **j** of the leaf (empty or not), the verifier can use the failed index verification using **j** and the key as proof that the key is not in the tree. Thus, the index **i** for the key does *not* need to be returned.

**Comment by c633** [comment]
related to #10

**Comment by arlolra** [comment]
> Since a proof of absence contains the full index j of the leaf (empty or not), the verifier can use the failed index verification using j and the key as proof that the key is not in the tree. Thus, the index i for the key does not need to be returned.

Can you explain that further, or sketch how it works?

Also, even if the index **i** is returned, what prevents the provider from returning _any_ leaf with a common prefix?

**Comment by masomel** [comment]
> Can you explain that further, or sketch how it works?

This is how I imagine this working. I go to lookup "alice" whose index is *i*. "alice" isn't in the key directory, but there is some other user in the directory whose index is *j* and has the longest prefix match with *i*. As part of the proof of absence, the key server returns *j*'s leaf node, allowing me to verify that ``vrf_verify(*j*, alice) = false``. Does this make sense?

> Also, even if the index **i** is returned, what prevents the provider from returning any leaf with a common prefix?

Nothing is preventing the provider from returning *any* leaf (with or without *i*, but at least with *i*, the client can verify that *j* has a common prefix). We considered this to be a form of denial of service, which the provider can do anyway, and which we can't really prevent. The only danger in this case is that the user/client won't care enough about the encryption and will decide to send a message in plain.

**Comment by arlolra** [comment]
> Does this make sense?

I'm not sure this constitutes a proof though.  All it tells me is that there's some leaf in the tree, not at **i**, that the provider is claiming shares a prefix with **i**.

Let's assume an honest provider that actually wants to prove to the client that the key isn't in the tree.

I'm not sure how to prove the absence without **i**. With it, I think you either need to return a empty leaf at **i**, or _two leaves_, of the same depth, with a common prefix to **i** and each other.  Something like that.

**Comment by masomel** [comment]
> I'm not sure this constitutes a proof though. 

Fair enough. It's not hard evidence like other proofs we generate.

> I'm not sure how to prove the absence without **i**. 

It's true, for a client to be absolutely sure that **i** isn't in the tree, the provider should probably return **i** along with a path. My main concern about revealing **i** as part of the proof of absence is that it would allow an attacker to slowly enumerate all absent **i**s in the tree. I assume the VRF is constructed such that this isn't an issue, but I'm not 100% sure about that.

> With it, I think you either need to return a empty leaf at **i**, 

Now, returning an empty leaf at **i** implies that the provider would have to initialized a tree representing the entire hash space of the private index, replacing empty nodes with actual user leaf nodes as the indexes become "taken". Otherwise, the provider would have to somehow perform some extra insertions into the existing tree to get a valid path with an empty leaf, thereby actually changing the tree without having an STR to bind the provider to the current tree contents (and we don't want to start creating a new STR for each individual update to the tree). 

> or two leaves, of the same depth, with a common prefix to **i** and each other. 

I kinda like this idea, though I don't know how common of a case this will be -- unless we pre-initialize the tree covering the entire private index space. I would really prefer to not do this for space reasons.

**Comment by arlolra** [comment]
> My main concern about revealing i as part of the proof of absence is that it would allow an attacker to slowly enumerate all absent **i**s in the tree.  I assume the VRF is constructed such that this isn't an issue, but I'm not 100% sure about that.

Worth verifying, yes.

> > or two leaves, of the same depth, with a common prefix to i and each other.

> I kinda like this idea, though I don't know how common of a case this will be -- unless we pre-initialize the tree covering the entire private index space. I would really prefer to not do this for space reasons.

I don't think this requires covering the entire index space.  The returned leaves can be either empty or user.  You just need two.  That way, you know there're no interior nodes beyond them that share a common prefix with **i**.  Do I have that right?

**Comment by arlolra** [comment]
> Do I have that right?

No, I don't have that right at all.  Nevermind me.

**Comment by arlolra** [comment]
Ok, I think what it is is that you need to show that **j** has the longest common prefix with **i**, which means where **i** and **j** diverge, it has to be a leaf. So, those are the two to return. Now, does that work?

**Comment by arlolra** [comment]
> Now, does that work?

Still no.

**Comment by arlolra** [comment]
From the paper,

> That node will either be a leaf node at depth l with an index i ̸= j which matches j in the first l bits, or an empty node whose index i is a prefix of j.

Wow, I'm dense.

**Comment by arlolra** [comment]
To be clear, `l` is part of the hash that ends up the the STR.  With that, yeah, that seems like proof.  I'll stop typing here now because I'm sure everyone is sick of me at this point.

**Comment by masomel** [comment]
No worries :) It's actually good to talk through our design decisions again and validate/invalidate them. I was confused myself for some time, which is why I opened this issue in the first place.

**Comment by masomel** [comment]
And the blurb from the paper does seem to imply that we still want to return **i** as part of the proof, so I think we have our answer.

**Comment by arlolra** [comment]
Yeah, I was going to say, the scheme your described w/o **i** didn't seem sufficient.  Agreed that we should return it (and also verify the assumption about the VRF above).

Thanks for showing pity :)

**Comment by c633** [comment]
So, just to confirm, the returned proof (or the auth path) would include both index **i** and **j**. And to verify the proof of absence, the user would check whether `vrf_verify(i, alice) == true && vf_verify(j, alice) == false`, right?

**Comment by arlolra** [comment]
I think the proof is like this,

* Verify the auth path of the returned leaf (which asserts index **j** at depth **l**)
* Check that where **i** and **j** differ is at bit **l**
* `vrf_verify(i, alice) == true`

If `j == i`, then the returned leaf should be empty and you can stop at 1.  Also, hopefully the VRF can't map alice to two different indices.

**Comment by c633** [comment]
> If j == i, then the returned leaf should be empty

Did you mean the returned leaf should be a `userLeafNode`? 

> Also, hopefully the VRF can't map alice to two different indices.

As I understand, the current VRF construction is collision resistance (which is explained in #5)

**Comment by Liamsi** [comment]
> As I understand, the current VRF construction is collision resistance (which is explained in #5)

It should provide about the same collision resistance as the used underlying hash function (in the case of the coname's VRF implementation sha3/shake256)

**Comment by arlolra** [comment]
> Did you mean the returned leaf should be a userLeafNode?

No, if `j == i` and the returned leaf is a user, then clearly alice isn't absent, right?

> As I understand, the current VRF construction is collision resistance

A collision would be if alice and bob map to the same index. What I'm saying (and what you wrote with `vrf_verify(i, alice) == true && vf_verify(j, alice) == false`) is that the VRF is repeatable (I don't know the right terminology). I mean that alice is always mapped to the same index.

**Comment by c633** [comment]
> No, if j == i and the returned leaf is a user, then clearly alice isn't absent, right?

Right, it's what I want to say. 

> A collision would be if alice and bob map to the same index. What I'm saying (and what you wrote with vrf_verify(i, alice) == true && vf_verify(j, alice) == false) is that the VRF is repeatable (I don't know the right terminology). I mean that alice is always mapped to the same index.

Sorry for the misreading :(

**Comment by arlolra** [comment]
> Sorry for the misreading :(

Don't be sad. Repeatability is something we depend on elsewhere (lookups and such) but really isn't a given in the construction. I can imagine a function that maps alice to various indices, that can all be verified (he says, waving his hands frantically).

**Comment by masomel** [comment]
Confirmed our assumptions about the VRF and enumerating all indices (via @jcb2):

>> we wanted to know if allowing an attacker to enumerate all i’s in this fashion will eventually allow the attacker to obtain the private VRF key?
>
> It shouldn't leak the VRF key ever. You can reveal as many VRF results as you want. ... this is just like if the user was present, right?
