### ISSUE TITLE
Per user salt

### ISSUE THREAD

**Issue by arlolra** [coniks-sys/libmerkleprefixtree-go#9]
> > ... you want a different nonce per-user so that you can selectively reveal, the tree nonce is for the whole tree.

> It looks to me that ```salt``` is also a tree-wide value. This needs to be changed.

@masomel can you elaborate on how you expect this to work?

**Comment by c633** [comment]
I think the `userLeafNode` struct should have `salt` field to store the `salt` value per user.
As suggested by [1][2] we would use a salt that is the same size as the output of the hash function (i.e. 128-bit). So the `salt` field should be an array of 16 bytes. 

[1] https://crackstation.net/hashing-security.htm#salt
[2] https://stackoverflow.com/questions/184112/what-is-the-optimal-length-for-user-password-salt

**Comment by arlolra** [comment]
The output of SHAKE128 that we're using is 256 bits though. So, if we're using the rule of thumb, let's get that right.

But maybe a 128 bit salt is fine. Let's see what @jcb82 says.

**Comment by masomel** [comment]
Sorry for my delay. Yes, what I had in mind is essentially what @c633 described. ```salt``` should be a field of the ```userLeafNode```, and I believe a new salt should be computed every time the ```value``` is updated.

**Comment by masomel** [comment]
I'm not certain what the size of the salt should be.

**Comment by arlolra** [comment]
Thomas Pornin says http://security.stackexchange.com/a/11224

**Comment by masomel** [comment]
So what this is saying is that we're probably fine with 128-bit salts generated at random, and we don't need to regenerate them each time the ```value``` is updated?

**Comment by masomel** [comment]
Nevermind, I misread part of that StackExchange response. As https://github.com/coniks-sys/libmerkleprefixtree-go/pull/8/files#r68285691 mentions, we *should* be replacing the salt every time the ```value``` changes. Sorry for going back and forth on this.

**Comment by arlolra** [comment]
Part of me thinks we should just reuse `HashSizeByte`.

**Comment by c633** [comment]
> Part of me thinks we should just reuse HashSizeByte.
Agree. Updated in 30123ed70d6ca2c67ff07e005a939fe92357f225

**Comment by arlolra** [comment]
Can you rebase the salt changes on master an open up a new pull for just this issue?
